### ISSUE TITLE
About MenuTrigger and Popup Menu inside a Modal 

### ISSUE THREAD

**Issue by WrathChaos** [instea/react-native-popup-menu#140]
Hello, 
First of all, I've opened a post on [StackOverflow](https://stackoverflow.com/questions/53744341/react-native-popup-menu-with-floatingactionbutton-component-cannot-trigger-with/53747989?noredirect=1#comment94482244_53747989). Still could not find a solution for that. 

Other and much more important question is that I have a use case which is I need to use PopupMenu in a Modal, that is why backDrop and tap to background to close the menu is not working. Can you provide me a solution or at least show me a way to make it happen?
Thank you so much :)

**Comment by sodik82** [comment]
popup menu can work also in modal however requires special handling due to how RN modal works. Pls see our [documentation](https://github.com/instea/react-native-popup-menu/blob/master/doc/api.md#menuprovider) for more details and/or https://github.com/instea/react-native-popup-menu/blob/master/examples/ModalExample.js

**Comment by sodik82** [comment]
as per your SO question - I tried to give generic advices how to deal with such situations but unfortunately I don't have time to try out every possible interactions with other 3rd party components.

**Comment by WrathChaos** [comment]
Thank you for reply @sodik82, I asked the first problem on SO but I could not reach any solution on there. I think I need to handle my use case with a special solution :) 

Thank you again, have fun
