### ISSUE TITLE
Incorrect work with ListView

### ISSUE THREAD

**Issue by igorpetrov** [instea/react-native-popup-menu#18]
Hi there!

I have a ListView component with cards and a popup menu placed on each card. Let's say I have 10 cards visible at the moment. When I click to open menu it calls Menu's `render()` method 40 times (four times on each card I suppose) and then open popup box. Of course performance is low and it looks laggy.

If I scroll to the end of the ListView and all cards become visible extra re-renders no longer occurs.

**Comment by sodik82** [comment]
yes, you are right that we are doing ~4 (re)renders (of MenuContext) when we are opening menu (we are measuring menu options, menu trigger and menu context so that we can finally properly open options on the screen). Thus it rerenders your listview 4 times => 40 times your cards with menu inside it.

We have basically the same situation in our production application and we were also noticing sometimes low performance. But the "root" cause of this performance were in our application - not directly in Menu. Rendering Menu is pretty cheap (unless you have very fancy trigger or options) but the problem was with rendering our Cards that have pretty complex structure and it was slowing our application when opening menu but also when doing other (menu unrelated) operations. He have solved it by applying proper `shouldComponentUpdate` to our cards component. For more details see [official React documentation](https://facebook.github.io/react/docs/optimizing-performance.html).

On the other hand 4 renders might not be necessary while opening menu - we might apply some tweaks to reduce the number. But it can't be better than 2 renders if we want to cover "generic case" - so the speed up would be by factor 2 - which is not bad but it won't mitigate the problems with high number of cards in your application.

**Comment by igorpetrov** [comment]
Thank you for clear explanation! Yes, `shouldComponentUpdate` did the trick.

Maybe It will not be superfluous to mention it in documentation for those who may be faced with this problem in future.

Cheers!

**Comment by sodik82** [comment]
we have reduced number of renders from 4 to 3. Further improvement is not possible without breaking changes in our extension API.
thanks for sharing your experience with us.
