### ISSUE TITLE
Feature Request: Can we set all MenuOptions to be horizontal?

### ISSUE THREAD

**Issue by KhalilKhalaf** [instea/react-native-popup-menu#34]
Beautiful and this popup menu is working like a charm. I was only wondering if we can implement the option where MenuOptions list can be displayed as a horizontal list instead of the current vertical one.

Please and thanks. And good work again.

**Comment by sodik82** [comment]
hi,
not exactly sure what exactly do you have in mind but you should be able to do it also now with the help of our [extension points](https://github.com/instea/react-native-popup-menu/blob/master/doc/extensions.md).

Might be even possible that you can achieve that purely with styling - see API or [example](https://github.com/instea/react-native-popup-menu/blob/master/examples/StylingExample.js).

I would be curious what you create (you can send me some screenshots/code samples :))

**Comment by KyleKhalaf** [comment]
@sodik82 I am trying to say that the current menu options, popup as a vertical list. If `MenuOptions` take a prop called `horizontal = true`, then the menu options will pop up as horizontal instead of vertical. (Remember `ListView` and its `horizontal` prop?)

Excuse my limited knowledge and language and if I can do it I will and provide you the solution but I don't know how. And thought of submitting this feature request which I thought would be very nice to have.

Thanks and good job

**Comment by sodik82** [comment]
So you would like to have "options" horizontally like `| Option1 | Option 2 | Option 3|`? Or maybe you can send me some screenshots/images from other applications that shows something like that.

However I would suggest you to start with simple gist (or repo) where you start experiment with styling or renderers so that I can see where have you got

**Comment by KyleKhalaf** [comment]
@sodik82  yes exactly. `Option1 | Option2 | Option3` And I will send a screen shot asap. Guide me where to start and I will give a shot as I am very new to react native. I come from C++ background so excuse me if I am overwhelming and thanks

**Comment by sodik82** [comment]
well, start making your application, study RN basic and especially [flexbox](https://facebook.github.io/react-native/docs/flexbox.html) and TouchableHighlight (and similar)
