### ISSUE TITLE
Very slow performance for large menus

### ISSUE THREAD

**Issue by joncursi** [instea/react-native-popup-menu#45]
I am using a popup menu to pick a country from a list of 196 countries. I am rendering custom `ListItem` elements for each country for minor styling (country flag + name) but the result is each item is a medium sized component of nested `View`, styles, etc. Multiply that times 196 `ListItem`s and the popup menu takes 5 seconds to open - it's not necessarily trivial to compute in one shot. The big problem is that the delay is causing users to tap it multiple times because they think they mis-tapped due to no visual feedback due to the lag, which causes the menu to close before it opens. Really suffering on the UX-front.

My guess here is that this library is rendering all items in one shot, so in my case React has to render this massive tree when the user taps to open the menu. Can we render list items in batch? `FlatList` has an `initialNumToRender` prop: https://facebook.github.io/react-native/docs/flatlist.html#initialnumtorender

* Version: I am on the latest version, but I've seen this issue in my app for pretty much all versions.

**Comment by madox2** [comment]
Hi, thanks for reporting! You are right, all menu options are rendered at once and that causes such slow performance. As a workaround you can use custom `renderOptionsContainer` with `FlatList`:

```javascript
const optionsRenderer = options => (
  <FlatList
    data={options.props.children}
    renderItem={({ item }) => React.cloneElement(item, {
      onSelect: options.props.onSelect
    })}
    style={{ height: 200 }}
  />
)
```

Here is the complete example: https://snack.expo.io/rylHyF-sb. This solution is however not very clean since it is relying on internal implementation of popup menu.

**Comment by sodik82** [comment]
hi, I will just add that we are actually rendering it twice (as we want to calculate the dimensions so that we can do "edge detection"). Current API is not very suitable for rendering of many items (however it is not frequent case).

However one trick came to my mind - render only one special menu option that will then render more options
```
const DynamicOptions = props => {
  const { data , ...others} = props
  return (
    <FlatList
      data={data}
      renderItem={({ item }) => <MenuOption {...others} value={item.value} key={item.key} text={item.value} />}
      style={{ height: 200 }}
    />
    )
}
...
        <Menu onSelect={value => Alert.alert(value)}>
          <MenuTrigger text="Select option" />
          <MenuOptions>
            <DynamicOptions data={data} />
          </MenuOptions>
        </Menu>
```
It is also little bit "hacky" but at least you don't need to render all menu options for closed menu - another performance gain (for application - not for opening the menu)

Expo link: https://snack.expo.io/HyzN95WjW

**Comment by joncursi** [comment]
Awesome stuff. Thanks for your prompt responses, my 196-long country menus are now blazing fast!

**Comment by sodik82** [comment]
(just for reference): with `0.10` it should be even easier: https://github.com/instea/react-native-popup-menu/blob/master/examples/FlatListExample.js
