### ISSUE TITLE
How to close popup menu on click out?

### ISSUE THREAD

**Issue by lorinerosenberg** [instea/react-native-popup-menu#54]
Is there a simple way of closing my PopUpMenu by clicking out of it? Like on blur with text input?

Thanks,

**Comment by sodik82** [comment]
it works out of the box (in standard case) - try yourself https://snack.expo.io/rkQrMFI8W

**Comment by juanjo-ramos** [comment]
It doesn't look like it follows that behaviour on UWP; i.e., tapping outside the popup doesn't close it. Has anyone tested it on Windows? I know it's not officially supported

**Comment by sodik82** [comment]
unfortunately we don't perform any UWP testing.

**Comment by juanjo-ramos** [comment]
Thanks for the update 👍

**Comment by iocuydi** [comment]
Does not close with click outside on ios

**Comment by sodik82** [comment]
Often it happens when `MenuProvider` is not covering screen (as it should according to documentation - it should be the root element).

Setting backdrop styles can confirm it... 

But if you can provide more information / insights about your issue, let us know

**Comment by iocuydi** [comment]
Thanks for the quick response! It was indeed due to my misuse of MenuProvider. I was opening the menu from a react-navigation header of a stacknavigator, and much of the body/background of the menu was intended to be the navigator page itself, which was a separate tabnavigator. I had only wrapped one of these in MenuProvider, when I moved the MenuProvider to wrap the entire app, it worked.

**Comment by hossamnasser938** [comment]
@creambyemute Thank you. This worked for me on uwp
