### ISSUE TITLE
Trouble having a PopUp render display 100% of the Device width to stretch

### ISSUE THREAD

**Issue by jeffreymendez1993** [instea/react-native-popup-menu#76]
Having trouble getting the popup menu to align correctly 100% of the container size. Theres always a small 10 px gap from the edge offset.

**Comment by sodik82** [comment]
hello, I would suggest you to play with custom styles https://github.com/instea/react-native-popup-menu/blob/master/doc/api.md#custom-styles-2

btw: by container you mean screen or something else? because menu is rendered outside of your component hierarchy to avoid problems with z-index.

if you thing it is a question, the best is to ask on stack overflow (with some sample code), if you think it is a bug, could you provide more details?
